version: "3"

services:
  bff:
    build: .
    expose: 
      - 3000
    ports:
      - '3000:3000'
    networks:
      - garden-land

networks:
  garden-land:
    name: garden-land
    external: true
